#%RAML 1.0 SecurityScheme
type: x-clientid-custom
description: Oauth Token Based Security
describedBy:
  headers:
    client_id:
      description: Client Id in base 64 format
    client_secret:
      description: Client Secret in base 64 format